### PR TITLE
feat: automate bacenta status to IC or graduated

### PR DESCRIPTION
**Pull request by AsiakN**
## Description
feat: automate bacenta status to IC or graduated

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

#### I tested it on my local 

- https://www.loom.com/share/5cb37a10c8d9467ab74dde0537b30fe4  --[Bacenta Status is maintained when Bacenta does not bus more than 8 or less than 8 for 4 consecutive weeks]

- https://www.loom.com/share/f2b7249d9d314257aabab39352e63530 -- [ Bacenta Status changes to Graduated when Bacenta busses more than 8 for 4 consecutive weeks.] 

- https://www.loom.com/share/542fc7eba56e4267bd2b088125e90267 -- [Change Bacenta status to IC when Bacenta busses less than 8 for 4 consecutive weeks]

### CODE REVIEW

**Comment by jaedag** [comment]
@AsiakN Why are there so many commits on this branch? Were you rebasing from deploy?

**Comment by jaedag** [comment]
Also @AsiakN you have to label the looks so that I know what I'm watching. What you've done doesn't help me

**Comment by AsiakN** [comment]
> Collaborator

Yes, I was.

**Comment by jaedag** [comment]
> > Collaborator
> 
> Yes, I was.

Okay. Please don't do that again. That's not how we work. It creates a lot of merge conflicts.

**Pull request merged**
