### PR TITLE
fix: import bacenta codes from Lp Ivy's list

### PR DESCRIPTION
**Pull request by dabick14**
## Description
This PR 
- corrects bacenta.code to bacenta.bacentaCode
- corrects topUp to lpIvyTopUp
- changes lastBacentaCode to one node instead of per stream
- imports codes from existing sheet

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How Has This Been Tested?
This has been tested on my localhost

## Screenshots/Videos (if appropriate):
Screenshot from 2022-11-19 15-18-28
Screenshot from 2022-11-19 18-34-10

### CODE REVIEW

**Comment by jaedag** [comment]
I don't understand. You put a screenshot instead of a video?

I don't understand the screenshot. It doesn't explain all the things in the PR that you have mentioned

**Review by jaedag — APPROVED** [review]

**Comment by jaedag** [comment]
@dabick14 Let me know if you get a notification for this one

**Comment by dabick14** [comment]
> @dabick14 Let me know if you get a notification for this one
> 
> 

Got the notification

**Review by jaedag — CHANGES_REQUESTED** [review]
@dabick14 Waiting for the final test of the DB with the cypher to confirm

**Comment by jaedag** [comment]
> > @dabick14 Let me know if you get a notification for this one
> 
> Got the notification @jaedag

Which means that mentions are the way forward. But do you get one for replies?

**Comment by dabick14** [comment]
> > > @dabick14 Let me know if you get a notification for this one
> 
> > 
> 
> > Got the notification @jaedag
> 
> 
> 
> Which means that mentions are the way forward. But do you get one for replies?

@jaedag there was a notification inside the GitHub app. But there was not push notification

**Comment by jaedag** [comment]
> > > > @dabick14 Let me know if you get a notification for this one
> > 
> > > 
> > 
> > > Got the notification @jaedag
> > 
> > 
> > 
> > Which means that mentions are the way forward. But do you get one for replies?
> 
> @jaedag there was a notification inside the GitHub app. But there was no push notification


Try replying to me the same way without a mention let's see

**Comment by dabick14** [comment]
> > > > > @dabick14 Let me know if you get a notification for this one
> > > 
> > > > 
> > > 
> > > > Got the notification @jaedag
> > > 
> > > 
> > > 
> > > Which means that mentions are the way forward. But do you get one for replies?
> > 
> > @jaedag there was a notification inside the GitHub app. But there was no push notification
> 
> 
> Try replying to me the same way without a mention let's see

I got a mention for this last comment.

**Review by jaedag — APPROVED** [review]

**Pull request merged**
