### PR TITLE
Shepherding control campaign

### PR DESCRIPTION
**Pull request by ahadziii**
## Description

Add the Shepherding Control Campaign

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How Has This Been Tested?

It has been tested on my local machine 

## Screenshots/Videos (if appropriate):
https://www.loom.com/share/ae11c9e4b92f4b759e88490ec36af065

### CODE REVIEW

**Comment by jaedag** [comment]
@ahadziii so 

1.  I need icons on these pages 

imageimage


2. I think the wording here is a whole mess. @dabick14 @ahadziii 
image

What we need is 
- Average Weekly Bussing Attendance 
- Average Weekly Weekday Attendance
- Average Weekly Weekday Income
- Cumulative Income for the Period

Sorry about the miscommunication, but please let the data reflect this

**Comment by jaedag** [comment]
We should modify the component so we no longer have these plain centered buttons. I feel they are becoming overused throughout the app.

**Comment by ahadziii** [comment]
@jaedag with the icons Klenam is coming up with some for me. He said it will be done by the time I'm done with campaigns

**Comment by jaedag** [comment]
> @jaedag with the icons Klenam is coming up with some for me. He said it will be done by the time I'm done with campaigns 

@ahadziii By the time you finish campaigns? To choose icons? 
That makes no sense. 

You have till tomorrow after church to finish.

**Review by jaedag — APPROVED** [review]

**Pull request merged**
