### PR TITLE
Admin 498 story/sheep seeking interface

### PR DESCRIPTION
**Pull request by ahadziii**
## Description

- Created a sheep seeking flow for GatheringService Admin
- Added screens for sheep seeker to add members and view membership
- add sheep seeking to campaign list if the user has stream or sheep seeking permissions

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How Has This Been Tested?

yes this has been tested on my local machine 

## Screenshots/Videos (if appropriate):

https://www.loom.com/share/7981b6fe14e04c95b9974469b933fb22
https://www.loom.com/share/a313b133ba9b43e89b82e234f4e15510

### CODE REVIEW

**Comment by jaedag** [comment]
@dabick14 is this the PR that will prevent fellowship leaders from being able to register members?

**Comment by dabick14** [comment]
> @dabick14 is this the PR that will prevent fellowship leaders from being able to register members?
> 
> 

@jaedag  yes sir.

**Comment by ahadziii** [comment]
@jaedag yes it is

**Comment by jaedag** [comment]
@ahadziii @dabick14 then let's take our time. Need to speak with B Josh before we go ahead

**Comment by dabick14** [comment]
> @ahadziii @dabick14 then let's take our time. Need to speak with B Josh before we go ahead

@jaedag yes sir. On standby.

**Review by jaedag — DISMISSED** [review]

**Comment by jaedag** [comment]
@ahadziii Unfortunately I took too long to review and now looks like there are some merge conflicts. Can you please resolve so I merge

**Comment by ahadziii** [comment]
@jaedag will have a look

**Review by jaedag — DISMISSED** [review]

**Comment by ahadziii** [comment]
@jaedag green light please

**Review by jaedag — APPROVED** [review]

**Pull request merged**
