### PR TITLE
feat: implement equipment defaulters for stream and gathering level a…

### PR DESCRIPTION
**Pull request by ahadziii**
…dmins

Implemented a defaulters flow so that gathering and stream admins can see those who didn't fill their forms 

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How Has This Been Tested?
yes in my localhost, I am hoping to engage @jaedag @dabick14 with further testing using the deploy preview

## Screenshots/Videos (if appropriate):

localhost_3000_campaigns_gathering-service_equipment_have-not-filled_fellowship(iPhone 6_7_8) (7)
localhost_3000_campaigns_gathering-service_equipment_have-not-filled_fellowship(iPhone 6_7_8) (6)
localhost_3000_campaigns_gathering-service_equipment_have-not-filled_fellowship(iPhone 6_7_8) (5)
localhost_3000_campaigns_gathering-service_equipment_have-not-filled_fellowship(iPhone 6_7_8) (4)
localhost_3000_campaigns_gathering-service_equipment_have-not-filled_fellowship(iPhone 6_7_8) (3)
localhost_3000_campaigns_gathering-service_equipment_have-not-filled_fellowship(iPhone 6_7_8) (2)
localhost_3000_campaigns_gathering-service_equipment_have-not-filled_fellowship(iPhone 6_7_8) (1)
localhost_3000_campaigns_gathering-service_equipment_have-not-filled_fellowship(iPhone 6_7_8)

### CODE REVIEW

**Comment by jaedag** [comment]
Try a video next time.

**Comment by jaedag** [comment]
And also… I thought we would have some breakdowns by church. 

So like from Gathering service to streams 
To councils

**Review by dabick14 — APPROVED** [review]

**Comment by dabick14** [comment]
I don't think that was included in the design

> And also… I thought we would have some breakdowns by church. 
> 
> 
> 
> So like from Gathering service to streams 
> 
> To councils

**Comment by ahadziii** [comment]
> And also… I thought we would have some breakdowns by church. 
> 
> 
> 
> So like from Gathering service to streams 
> 
> To councils 

I was using the design by Klenam

**Review by jaedag — APPROVED** [review]

**Review by jaedag — APPROVED** [review]

**Comment by jaedag** [comment]
@ahadziii Please resolve the merge conflicts here

**Pull request closed without merging**
