### PR TITLE
Refactor/admin 311 anagkazo banking by constituencies

### PR DESCRIPTION
**Pull request by dabick14**
## Description

This PR does two things:
1. It provides a list of constituencies that have not been confirmed as banked (Anagkazo Stream)
2. It allows the confirmer to confirm an entire constituency and mark all it's fellowships as banked when confirmed.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## How Has This Been Tested?
This has been tested on my localhost and proved to be working

## Screenshots/Videos (if appropriate):
https://drive.google.com/file/d/1VVXVIP77vCCebXflnUISLPAAJJOUtVn2/view?usp=sharing (video is too large for github)

### CODE REVIEW

**Comment by jaedag** [comment]
LOL chief. You couldn't compress the video a bit? The G Drive also wants me to download.

**Comment by jaedag** [comment]
@ahadziii Do you know how to commit directly to this branch without forking? That's why I was calling you

**Comment by ahadziii** [comment]
> @ahadziii Do you know how to commit directly to this branch without forking? That's why I was calling you

let me try

**Comment by jaedag** [comment]
Ah @ahadziii why are you also pushing merge commits

**Comment by ahadziii** [comment]
When I pushed the code there were conflicts. Which I resolved on GitHub but it still brought this up

**Pull request merged**
